- name: Prepare for Shutdown
  ansible.builtin.debug:
    msg: "{{ database_name }} is preparing to shutdown..."

- name: Finished Shutdown
  ansible.builtin.debug:
    msg: "{{ database_name }} is down! :("
