- name: "Stop {{ inventory_hostname }}"
  ansible.builtin.include_tasks: states/down.yml
  when: state == "down"
  
- name: "Start {{ inventory_hostname }}"
  ansible.builtin.include_tasks: states/up.yml
  when: state == "up"
  