- name: "{{ inventory_hostname }} Stopping..."
  ansible.builtin.include_tasks: states/down.yml
  when: state == "down"
  
- name: "{{ inventory_hostname }} Starting..."
  ansible.builtin.include_tasks: states/up.yml
  when: state == "up"
  