# File: activate.yml
# Purpose: This file would be used to activate the new environment such that it becomes the live environment.
# Optional: No
---
- name: Activate
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "Environment has been activated!!!"
