# File: activate.yml
# Purpose: This file would be used to activate the new environment such that it becomes the live environment.
# Optional: No
---
- name: Swap DNS
  hosts: dns
  gather_facts: false

  roles:
    - role: dns_flip

- name: Completed
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ environment_name }} has been activated!"


    - name: Print super secret password
      ansible.builtin.debug:
        msg: "{{ password }} has been used!"
