# File: check.yml
# Purpose: This file would be used to check the new environment for any automated testing which
#          could be used to verify environment availability.
# Optional: No
---
- name: Check
  hosts: all
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ environment_name }} is testing all the things..."
