# File: cleanup.yml
# Purpose: This file would be used to activate the new environment such that it becomes the live environment.
# Optional: No
---
- name: Cleanup
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "The cleanup tasks have been performed."
