# File: deactivate.yml
# Purpose: This file would be used to bring an environment down to a cool state.
# Optional: Yes
---
- name: Deactivate
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ environment_name }} has been deactivated!!!"
