# File: down.yml
# Purpose: This file would be used to bring an environment down to a cold state.
# Optional: No
---
- name: Notify starting to shutdown
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "Environment is stopping..."

- name: Oracle
  hosts: oracle
  gather_facts: false

  roles:
    - role: oracle_down

- name: Cleanup
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "Environment is down! :("
