# File: down.yml
# Purpose: This file would be used to bring an environment down to a cold state.
# Optional: No
---
- name: Prepare
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ environment_name }} is stopping..."

- name: Oracle
  hosts: oracle
  gather_facts: false
  roles:
    - role: oracle_failover
      vars:
        state: down

- name: Cleanup
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ environment_name }} is down! :("
