---
- name: Env1 to Env2
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "Env 2 is starting..."

    - name: Print Message
      ansible.builtin.debug:
        msg: "Env 2 is up! :)"

    - name: Print Message
      ansible.builtin.debug:
        msg: "Testing all the things..."

    - name: Print Message
      ansible.builtin.debug:
        msg: "Dns has been changed!"

    - name: Print Message
      ansible.builtin.debug:
        msg: "Env 1 is stopping..."

    - name: Print Message
      ansible.builtin.debug:
        msg: "Env 1 is down! :("
