---
- name: Env1 to Env2
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Start Env2
      ansible.builtin.include_role:
        name: up
      vars:
        up_env: env2

    - name: Check Env2
      ansible.builtin.include_role:
        name: check
      vars:
        check_env: env2

    - name: Test Env2
      ansible.builtin.pause:
        prompt: Proceed with testing env2

    - name: Activate Env2
      ansible.builtin.include_role:
        name: activate
      vars:
        activate_env: env2

    - name: Down Env1
      ansible.builtin.include_role:
        name: down
      vars:
        down_env: env1
