---
- name: Env2 to Env1
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Start Env1
      ansible.builtin.include_role:
        name: up
      vars:
        up_env: env1

    - name: Check Env1
      ansible.builtin.include_role:
        name: check
      vars:
        check_env: env1

    - name: Activate Env1
      ansible.builtin.include_role:
        name: activate
      vars:
        activate_env: env1

    - name: Down Env2
      ansible.builtin.include_role:
        name: down
      vars:
        down_env: env2
