---
- name: Down
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ up_env }} is stopping..."

    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ up_env }} is down! :("
