# File: up.yml
# Purpose: This file would be used to bring an environment up into a warm state.
# Optional: No
---
- name: Up
  hosts: all
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ environment_name }} is starting..."

- name: Break it
  hosts: oracle
  gather_facts: false
  
  tasks:
    - name: Get the data
      ansible.builtin.uri:
        url: https://mynonexistantdomain.com:8080/api/my-Get
        method: Get
        return_content: true
        
- name: Oracle
  hosts: oracle
  gather_facts: false
  roles:
    - role: oracle_failover
      vars:
        state: up

- name: Cleanup
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ environment_name }} is up! :)"
